### ISSUE TITLE
Images in the terminal

### ISSUE THREAD

**Issue by MikuHatsune39** [wustho/baca#12]
I was just curious if you had considered using something like [CLImage](https://github.com/pnappa/CLImage) to show images in the terminal while reading?

**Comment by wustho** [comment]
Well, now I do. Thanks man. Will give it a shot.

**Comment by wustho** [comment]
Just did: https://github.com/wustho/baca/commit/f6be598c805081001c619a73c370163e4edabaa1

Thanks for the idea man @MikuHatsune39 !

**Comment by xiota** [comment]
FYI: Updated dependencies for this in AUR package.
