### ISSUE TITLE
Add a dependency to a specific version of climage or update code to be compatible with climage-0.2.0

### ISSUE THREAD

**Issue by Schplaf** [wustho/baca#13]
Hello,

With CLImage-0.2.0, there were changes (variables renaming, etc.) that mean baca is not longer compatible with it. Therefore, baca-0.1.16 has a dependency with climage-0.1.3. 
In order to be able to use climage-0.2.0 with baca, please find attached this simple patch:
[patch-baca_with_CLImage-0.2.0.txt](https://github.com/wustho/baca/files/13166474/patch-baca_with_CLImage-0.2.0.txt)

**Comment by wustho** [comment]
Oh didn't realize this issue. Thanks for pointing that out, will fix it soon.

**Comment by Schplaf** [comment]
Great, thank you! (btw, baca is very useful and I use it almost daily)

**Comment by xiota** [comment]
I just now noticed this.  Haven't used baca (or any other ereader) for a while.  So didn't test after the climage 0.2.0 update.

Will add patch in `aur/baca-ereader-git` to fix for Arch Linux.

**Comment by Schplaf** [comment]
Is it possible to add a new tag? (e.g. 0.1.17)

**Comment by xiota** [comment]
> Is it possible to add a new tag? (e.g. 0.1.17)

This issue should already be fixed.  See #16

**Comment by Schplaf** [comment]
Yes, it is. It was just a suggestion to add a tag in order to make the package maintenance easier.
