### ISSUE TITLE
Spacing Issue

### ISSUE THREAD

**Issue by dattlab** [wustho/baca#2]
There are some words that are not properly spaced. The pattern where they occur is kinda like in a diagonal way.

### `baca`
![baca](https://user-images.githubusercontent.com/122553391/228025666-c0fdfb73-97e7-41c1-98d3-4199885fdea4.png)

### Calibre EPUB Viewer:
![calibre](https://user-images.githubusercontent.com/122553391/228023370-26b86956-6c29-4b9a-8415-a3e82de0b946.png)

**Comment by wustho** [comment]
Hey there, that's strange, I cannot reproduce it. Can you by any chance send me the ebook file so I con look into it closer? It would be useful for the development of this program

**Comment by wustho** [comment]
Oh I think I see the issue, just tried fixing it. Can you @dattlab update via `pip install --upgrade baca` and see if the issue still persists?

**Comment by dattlab** [comment]
It's fixed now. Thanks!

![image](https://user-images.githubusercontent.com/122553391/228100376-80e96dd7-b4a1-431a-82be-217eb5087145.png)
