### ISSUE TITLE
Image box's right border issue

### ISSUE THREAD

**Issue by dattlab** [wustho/baca#4]
Image box's right border stays at the right side while scrolling

Test epub 1
![Peek 2023-03-28 12-01](https://user-images.githubusercontent.com/122553391/228128767-7b783d38-742a-40c2-b780-283d2680d124.gif)

Test epub 2
![Peek 2023-03-28 12-29](https://user-images.githubusercontent.com/122553391/228128788-41f02f4f-a981-4e52-a7b3-231fb5ed38d8.gif)

**Comment by wustho** [comment]
Hmm, just recreated in kitty terminal, but works fine in other terminal emulators. Will look into that.

**Comment by wustho** [comment]
Just found the issue, it's caused by symbol: 🖼️. Will fix the issue later.

**Comment by wustho** [comment]
@dattlab Just fixed, let me know if the issue still persists.
