### ISSUE TITLE
Error opening an image: [Win Error 2]

### ISSUE THREAD

**Issue by stone2forge** [wustho/baca#6]
**baca v0.1.11** cannot open images when clicking the large `IMAGE` box. 

I've already tried with several other books I own as well as the ones freely available at [Project Gutenberg](https://www.gutenberg.org/).

![image](https://user-images.githubusercontent.com/76193584/229649921-0d5b925b-e251-431d-91ad-a979e524619c.png)

## Steps to reproduce 

1. Download any e-book ([this one preferably](https://www.gutenberg.org/ebooks/70456.epub3.images)).
2. Open the Terminal and direct baca to the e-book path (either by dragging it through the File Explorer or typing it by hand)
3. Click `IMAGE` box
4. baca will show a `[Win Error 2]` error.

**Comment by wustho** [comment]
Hey there, can you try uninstall baca then reinstall it using this branch: `pip install git+https://github.com/wustho/baca@issue/win/img-file-not-found`

And see if the issue still persists? I don't have windows machine, so I cannot try it for myself. Thanks.

**Comment by stone2forge** [comment]
Problem remains, even tried on a new virtual environment 😔.

**Comment by wustho** [comment]
Oh, just understood the issue, @stone2forge 
Can you try again with `pip install git+https://github.com/wustho/baca@issue/win/img-file-not-found`
And see if it works now?

**Comment by stone2forge** [comment]
Can confirm it works now!

**Comment by wustho** [comment]
Thanks mate, appreciate it! Now it's in main branch, and we can install it via `pip install --upgrade baca`
