### ISSUE TITLE
Screenshot?

### ISSUE THREAD

**Issue by willmcgugan** [wustho/baca#7]
Hello,

Textual dev here. We are building a little showcase of apps for the docs / website.

Would you mind if we put a screenshot of Baca there? With a link to the repo of course.

**Comment by wustho** [comment]
@willmcgugan not at all! In fact, it'd be my pleasure! Yeah I know you're textual dev by your username!

**Comment by wustho** [comment]
@willmcgugan not at all! In fact, it'd be my pleasure!

**Comment by willmcgugan** [comment]
Fantastic! Would you mind taking a SVG screenshot for us?

If you run the app like this, it will write a screenshot after 10 seconds then exit...

```python
textual run app.py --screenshot 10
```

**Comment by wustho** [comment]
Sorry, it was late in my timezone. Here are the screenshots, feel free to choose any of these and let me know if you need anything else @willmcgugan 
![baca_2023-04-07T11_04_20_114333](https://user-images.githubusercontent.com/43810055/230538839-fd1bc718-fcf6-44db-bb18-0bccea167838.svg)
![baca_2023-04-07T11_04_07_269136](https://user-images.githubusercontent.com/43810055/230538842-c6a0ed7e-6c50-4972-8ea7-e64c4a07cae4.svg)
![baca_2023-04-07T11_03_51_876877](https://user-images.githubusercontent.com/43810055/230538847-641c0338-5e2d-4917-9afe-78be3f999a9b.svg)
![baca_2023-04-07T11_03_36_461122](https://user-images.githubusercontent.com/43810055/230538849-b9e6ef8a-c3bb-492a-a69a-f23d1ff9aeef.svg)
![baca_2023-04-07T11_03_18_188385](https://user-images.githubusercontent.com/43810055/230538852-c42f530e-53cc-4cf7-9f57-7eeb55943f15.svg)

**Comment by willmcgugan** [comment]
That's perfect! Thanks so much.
