### ISSUE TITLE
switch from fuzzywuzzy to thefuzz?

### ISSUE THREAD

**Issue by xiota** [wustho/baca#8]
Upstream renamed `fuzzywuzzy` to `thefuzz`.

* https://github.com/seatgeek/fuzzywuzzy
* https://github.com/seatgeek/thefuzz

No urgency in switching because the Linux repositories I checked still provide `python-fuzzywuzzy`.  But since it's apparently only a name change, maybe something like the following would work:
```python
try:
    import thefuzz as fuzzywuzzy
except:
    import fuzzywuzzy
```

**Comment by AnonymouX47** [comment]
What's the point of this when the dependency is specified? 🤔

https://github.com/wustho/baca/blob/8312be39d89fc8fe4369ab4ea757ada60b370613/pyproject.toml#L22

Since `baca` requires `python>=3.10`, why even use `fuzzywuzzy` at all?
I think both the dependency and the import should just be changed entirely... or am I missing something?

**Comment by wustho** [comment]
Thanks for bringing that up @AnonymouX47 , at that time I only checked pypi page for fuzzywuzzy, so I didn't know that it was renamed to thefuzz, hence that issue. WIll fix this later.

**Comment by wustho** [comment]
And the PR is a prep for dependency change, no rush.

**Comment by xiota** [comment]
Depending on how programs are packaged, dependency lists can be treated as suggestions.  Once installed, the program will use what's available.  So distros that provide `thefuzz` can begin testing, even though the package still specifies "fuzzywuzzy".

There is another python program (from a different dev) that lists half a dozen modules as "dependencies" that it doesn't even use.  The versions it lists are also mostly out of date and don't match what's available in modern systems.  Cleanest way to install it is to ignore the dependency list.

**Comment by AnonymouX47** [comment]
Oh, Ok.

**Comment by wustho** [comment]
Closing this one as it's already done
